### ISSUE TITLE
C# Assemblies Not Strong Named On Mono

### ISSUE THREAD

**Issue by martincostello** [experiandataquality/electronicupdates#12]
During the work for PR #6 to support building the C# sample code on Linux it was found that the compiled assemblies are not strong named for some reason. This needs to be fixed so that the Windows and Linux builds produce equivalent compiled assemblies.

Once resolved, the `#if UNIX` in [AssemblyInfo.cs](https://github.com/experiandataquality/electronicupdates/blob/84a0636dffea38119915e7f083e6a9f9d21a603f/src/CSharp/MetadataWebApi/MetadataWebApi/Properties/AssemblyInfo.cs#L19-22) needs to be removed so the `[InternalsVisibleTo]` attributes are applied correctly.

**Comment by martincostello** [comment]
After some research I can't figure out why this is not working. Logged as [Bug 30093](https://bugzilla.xamarin.com/show_bug.cgi?id=30093) in Xamarin's Bugzilla issue tracker.

**Comment by Lexcess** [comment]
Latest PR will remove Strong naming from the code which coincidentally resolves this issue.
